version: '3.2'
services:
    localstack:
        image: localstack/localstack:0.11.6
        container_name: localstack
        environment:
            - HOSTNAME_EXTERNAL=localhost
            - SERVICES=sqs
            - DEBUG=1
            - DEFAULT_REGION=eu-central-1
        ports:
            - '4563-4599:4563-4599'
            - '8055:8080'
